# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - marstourist

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://webappsandapis.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_34c2c969f8c44a2f8b9903179edbc0f0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bc64e7ad3e5a4216ac81815ec3c02ad9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: webappsandapis.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_34c2c969f8c44a2f8b9903179edbc0f0 }}/marstourist:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'marstourist'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2f898d1ec0304638aecccff38e33d6db }}
        images: 'webappsandapis.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_34c2c969f8c44a2f8b9903179edbc0f0 }}/marstourist:${{ github.sha }}'